### ISSUE TITLE
Support For Notification

### ISSUE THREAD

**Issue by itskrsna** [EltonFaust/cordova-plugin-multi-player#1]
Can you provide support for the notification as `cordova-plugin-streaming` is providing ..

Any reason to remove it?

**Comment by EltonFaust** [comment]
Sorry but i am not going to add notification support, i am using this to my own project, and on my project i need to continuously update the music controls notification content...

You can use another plugin to set the music control notification, like i am doing....

I am using this plugin: [Cordova Music Controls Plugin](https://github.com/homerours/cordova-music-controls-plugin)

**Comment by itskrsna** [comment]
Thanks for the Reply , will that plugin support Shoutcast streaming, because i couldn't find in their README.md

**Comment by EltonFaust** [comment]
I've not tried any shoutcast stream, but has some code referencing to shoutcast on aacdecoder library (used to play the stream), i guest it will work, but i can't guarantee, sorry...

**Comment by itskrsna** [comment]
Are you referring to the RadioPlayerService ? if so i have used it , but that repo isn't updated from a long time. can you please share me the reference code , if we are using other than RadioPlayerService ?

**Comment by EltonFaust** [comment]
The aacdecoder library i am referring to is located [here](https://github.com/EltonFaust/cordova-plugin-multi-player/tree/master/src/android/libs/aacdecoder), its based on [this fork](https://github.com/PeterRinc/aacdecoder-android) of [aacdecoder library](https://github.com/vbartacek/aacdecoder-android).

The RadioPlayerService class on method getPlayer, you can find a try catch block that is responsible to handle shoutcast streams, but as i said i dont tested on a shoutcast stream...

**Comment by itskrsna** [comment]
@EltonFaust  Thanks for this will give a try with the info you have given ..
Closing this issue..
