### ISSUE TITLE
Exoplayer deprecated? 

### ISSUE THREAD

**Issue by matias-tecnosoul** [EltonFaust/cordova-plugin-multi-player#19]
Hi, I was getting this error when building
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android.exoplayer:exoplayer:2.11.8.
     Required by:
         project :app
      > Could not resolve com.google.android.exoplayer:exoplayer:2.11.8.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/exoplayer/exoplayer/2.11.8/exoplayer-2.11.8.pom'.
            > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/exoplayer/exoplayer/2.11.8/exoplayer-2.11.8.pom'.
               > Certificate for <google.bintray.com> doesn't match any of the subject alternative names: [*.jfrog.io, *.int.jfrog.io, jfrog.io, *.pe.jfrog.io]

following gpt's advice i adjusted the url and version in build.gradle:

```
allprojects {
    repositories {
        google()
         mavenCentral()
    // jcenter() // Deprecated, avoid using if possible
       /* maven {
            url 'https://google.bintray.com/exoplayer/'
        }*/
    }
}

dependencies {
    implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
}
```

It sempt to install it correctly. 
Now:

> Task :app:compileDebugJavaWithJavac FAILED
radio-player-base/src-cordova/platforms/android/app/src/main/java/com/eltonfaust/multiplayer/RadioPlayerService.java:408: error: cannot find symbol
    private ExoPlayer.EventListener playerEventListener = new ExoPlayer.EventListener() {
                     ^
  symbol:   class EventListener
  location: interface ExoPlayer
radio-player-base/src-cordova/platforms/android/app/src/main/java/com/eltonfaust/multiplayer/RadioPlayerService.java:359: error: constructor DefaultBandwidthMeter in class DefaultBandwidthMeter cannot be applied to given types;
            DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
                                                   ^
  required: Context,Map<Integer,Long>,int,Clock,boolean
  found:    no arguments
  reason: actual and formal argument lists differ in length

Do you have any tips i can try?
thanks in advance!

**Comment by matias-tecnosoul** [comment]
sorry, I've just seen your PR abouta migrating to media3! :D
https://github.com/EltonFaust/cordova-plugin-multi-player/pull/18

in the meanwhile , is it possible to to make it work with old exoplayer version?

thanks for the plugin btw!

**Comment by EltonFaust** [comment]
Hello Matias,

The gpt solution wont work, the devs from exoplayer renamed a lot of the methods and classes, that is your latest error cause.

I dont know for how long the 2.19.1 will be available in the google repos, so I already upgraded to the latest ExoPlayer version.

If you want to remain in the current version, the only solution I can think of is if you find some maven repo that has the POMs from the 2.11.8 version, or fork the master from my repository and refactor the code with the new classes/methods.

If you want to use the upgrade you can use directly from my branch:
```sh
# remove the current version
cordova plugin remove cordova-plugin-multi-player
# add directly from my branch on github
cordova plugin add https://github.com/EltonFaust/cordova-plugin-multi-player#upgrade-to-androidx.media3
```

**Comment by matias-tecnosoul** [comment]
great! will try that branch, thanks a lot!! :+1:
