### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by matias-tecnosoul** [EltonFaust/cordova-plugin-multi-player#6]
Hi, I'm testing the plugin and seems to be working great with the "background" playing which is why I started using it :)
I'm having a couple of doubts regarding the notifications.
Whenever the app starts playing the stream (its an online radio stream) it shows up a bubble or badge over the app icon, and also shows a message in the Android notification area saying that the "app is running" and gives me options to close or uninstall the app which is something I dont see with other apps.
I enclose a couple of screenshots.
[scrrenshot1](https://drive.google.com/open?id=13J1-RhhSeujcpDj2_ZUxpvBTOh2ISxCQ)
[scrrenshot2](https://drive.google.com/open?id=13I9m2uXwCgyapGmNTF_7VnsJtRfBCh6A)
I know this might not be an issue of this plugin but I can't seem to find info about the neccessary configuration.
Thanks a lot for the plugin and for any advice on where to look now!

**Comment by EltonFaust** [comment]
Hello,

To create a backgroud service is required to create a notification, previously on android 8 and older versions, to run a service on background was allowed to create a "hidden" notification, but on android 8.1 and later, that wasn't allowed anymore, so you need a visible notification showing to the user that there is a service running on background.

The propose of this plugin is to play the streaming, so i didn't created a fancy notification, if you want to display a notification with information and a play/pause button, you can use [cordova-music-controls-plugin](https://github.com/homerours/cordova-music-controls-plugin).

If you create the notification with the [cordova-music-controls-plugin](https://github.com/homerours/cordova-music-controls-plugin) before you start playing the streaming, the streaming plugin will use this notification for the service, so will not create the "Process is running" notification.

The plugin [cordova-music-controls-plugin](https://github.com/homerours/cordova-music-controls-plugin) has features that will be usefull to you, so i recommend using both plugins together...

**Comment by matias-tecnosoul** [comment]
Great, much clearer now! and that plugin combination sounds very interesting, I'll definitely give it a try.
Thanks so much for your plugin and recommendations!
